# Generated by Django 4.2.10 on 2024-02-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_otp_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
